GET http://localhost:3001/api/notes/
###
GET http://localhost:3001/api/notes/62cafcdc844aece508e73eea
###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-Type: application/json

{
    "content":  "VS Code REST Client is pretty Awesome",
    "important": false
}
###
DELETE http://localhost:3001/api/notes/4 HTTP/1.1
###
DELETE  http://localhost:3001/api/persons/54 HTTP/1.1
###
GET http://localhost:3001/api/persons/
### 
POST  http://localhost:3001/api/persons/ HTTP/1.1
content-Type: application/json

{
    "name": "Samuel Damilare",
    "number": 1354587
}
